### ISSUE TITLE
Results of static scanning may be incomplete

### ISSUE THREAD

**Issue by metamorfosec** [zoffixznet/Mojo-PDF#13]
Hello,
Could you check this issue?
Thank you.
Regards.

perl -v
`This is perl 5, version 32, subversion 1 (v5.32.1) built for MSWin32-x64-multi-thread`

Example code:
```
# test_mojopdf.pl
use strict;
use warnings;
use utf8;
use diagnostics;

use Mojo::PDF;

Mojo::PDF->new('mypdf.pdf')->text('Viva la Mojo!', 306, 396)->end;
```
pp:
`pp -o test_mojopdf.exe test_mojopdf.pl -c -x`

Results:
```
# Use of runtime loader module Module::Implementation detected.  Results of static scanning may be incomplete.
# Use of runtime loader module Module::Runtime detected.  Results of static scanning may be incomplete.
```

**Comment by zoffixznet** [comment]
Sorry, I don't use windows or pp. This module is just a wrapper over [PDF::Reuse](https://metacpan.org/pod/PDF::Reuse). I suspect the way it loads things is what's causing those messages. Try to talk to the other of that module.
